export const THEMES: Record<string, string[]> = {
  Animals: ['TIGER', 'ZEBRA', 'OTTER', 'PANDA', 'MOOSE', 'EAGLE', 'SHARK', 'CAMEL', 'LLAMA', 'KOALA', 'BISON', 'RAVEN', 'HORSE', 'GECKO', 'WHALE'],
  Fruits: ['APPLE', 'MANGO', 'GRAPE', 'LEMON', 'PEACH', 'CHERRY', 'BANANA', 'KIWI', 'PAPAYA', 'MELON', 'GUAVA', 'PLUM', 'LIME', 'APRICOT'],
  Space: ['PLANET', 'COMET', 'ORBIT', 'GALAXY', 'NEBULA', 'ROCKET', 'METEOR', 'SATURN', 'MARS', 'VENUS', 'LUNAR', 'STAR', 'ASTEROID', 'SOLAR'],
  Ocean: ['CORAL', 'WAVE', 'TIDE', 'REEF', 'SQUID', 'SHELL', 'KELP', 'OCTOPUS', 'DOLPHIN', 'ANCHOR', 'HARBOR', 'PEARL', 'CRAB'],
  Sports: ['SOCCER', 'TENNIS', 'HOCKEY', 'RUGBY', 'GOLF', 'BOXING', 'SKIING', 'KARATE', 'CYCLING', 'ROWING', 'CRICKET', 'SURFING', 'POLO'],
  Music: ['GUITAR', 'PIANO', 'DRUMS', 'VIOLIN', 'TEMPO', 'CHORD', 'MELODY', 'RHYTHM', 'OPERA', 'FLUTE', 'BASS', 'HARP', 'BANJO', 'LYRIC'],
  Weather: ['STORM', 'RAIN', 'SNOW', 'THUNDER', 'CLOUD', 'BREEZE', 'SUNNY', 'FROST', 'HAIL', 'FOG', 'RAINBOW', 'TORNADO', 'DRIZZLE'],
  Kitchen: ['SPOON', 'KNIFE', 'FORK', 'PLATE', 'OVEN', 'KETTLE', 'WHISK', 'BOWL', 'LADLE', 'GRILL', 'TOASTER', 'BLENDER', 'APRON'],
  Colors: ['CRIMSON', 'AZURE', 'AMBER', 'VIOLET', 'INDIGO', 'SCARLET', 'TEAL', 'IVORY', 'OLIVE', 'MAGENTA', 'BEIGE', 'CYAN'],
  Tech: ['LAPTOP', 'PIXEL', 'ROBOT', 'CODE', 'MOUSE', 'SCREEN', 'CABLE', 'CHIP', 'SERVER', 'BINARY', 'ROUTER', 'BATTERY'],
  Nature: ['FOREST', 'RIVER', 'MEADOW', 'CANYON', 'VALLEY', 'DESERT', 'GLACIER', 'ISLAND', 'VOLCANO', 'LAGOON', 'CLIFF', 'MOSS'],
  Travel: ['TICKET', 'PASSPORT', 'AIRPORT', 'HOTEL', 'MAP', 'LUGGAGE', 'CRUISE', 'TRAIN', 'BEACH', 'VISA', 'TOUR', 'SUITCASE'],
};
